### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by WhiffleFish** [qhho/CGCP.jl#2]
https://github.com/qhho/CGCP.jl/blob/49d91eb73689bfdda26acf06892d29c69a33d194/src/solver.jl#L127-L131

Possible race condition here, same as one outlined in this [wikipedia example](https://en.wikipedia.org/wiki/Race_condition#Example).

**Comment by qhho** [comment]
The original CGCP algorithm does not use monte carlo simulation to compute V and C, but instead uses a policy graph. @bkraske is currently implementing the policy graph which will replace this MC simulation.

**Comment by bkraske** [comment]
Addressed with [324590c](https://github.com/qhho/CGCP.jl/commit/324590c95063f25de8d6f093bb0db9789d500654)
